export interface Job {
  id: string
  slug: string
  referenceCode: string
  title: string
  titleCs: string
  location: string
  locationCs: string
  type: 'inhouse' | 'lawfirm'
  level: string
  industry: string
  industryCs: string
  shortDescription: string
  shortDescriptionCs: string
  fullDescription: string
  fullDescriptionCs: string
  responsibilities: string[]
  responsibilitiesCs: string[]
  requirements: string[]
  requirementsCs: string[]
  featured: boolean
}

export const jobsData: Job[] = [
  {
    id: '1',
    slug: 'general-counsel-prague',
    referenceCode: 'BS-2024-001',
    title: 'General Counsel',
    titleCs: 'General Counsel',
    location: 'Prague',
    locationCs: 'Praha',
    type: 'inhouse',
    level: 'C-Level',
    industry: 'Technology',
    industryCs: 'Technologie',
    shortDescription: 'Leading technology company seeking an experienced General Counsel to lead their legal function across CEE.',
    shortDescriptionCs: 'Přední technologická společnost hledá zkušeného General Counsel k vedení právní funkce v CEE.',
    fullDescription: 'A rapidly growing technology company with operations across Central and Eastern Europe is seeking a General Counsel to lead their legal function. This is a pivotal leadership role reporting directly to the CEO, with full responsibility for all legal matters across the region.',
    fullDescriptionCs: 'Rychle rostoucí technologická společnost s operacemi ve střední a východní Evropě hledá General Counsel k vedení své právní funkce. Jedná se o klíčovou vedoucí roli s přímou reportovací linií k CEO a plnou odpovědností za veškeré právní záležitosti v regionu.',
    responsibilities: [
      'Lead and develop the in-house legal team across multiple jurisdictions',
      'Provide strategic legal counsel to the executive leadership team',
      'Oversee all corporate governance and compliance matters',
      'Manage external counsel relationships and legal budgets',
      'Support M&A activities and commercial negotiations',
      'Develop and implement legal policies and procedures',
    ],
    responsibilitiesCs: [
      'Vést a rozvíjet interní právní tým napříč jurisdikcemi',
      'Poskytovat strategické právní poradenství výkonnému vedení',
      'Dohlížet na veškeré záležitosti corporate governance a compliance',
      'Řídit vztahy s externími advokáty a právní rozpočty',
      'Podporovat M&A aktivity a obchodní vyjednávání',
      'Vyvíjet a implementovat právní politiky a postupy',
    ],
    requirements: [
      '15+ years of legal experience, with significant in-house experience',
      'Proven leadership experience managing legal teams',
      'Strong background in technology sector or regulated industries',
      'Fluent English; Czech or other CEE languages advantageous',
      'Excellent commercial acumen and business partnership skills',
      'Experience with cross-border transactions and multi-jurisdictional matters',
    ],
    requirementsCs: [
      '15+ let právní praxe, s významnou in-house zkušeností',
      'Prokázané zkušenosti s vedením právních týmů',
      'Silné zázemí v technologickém sektoru nebo regulovaných odvětvích',
      'Plynulá angličtina; čeština nebo jiné jazyky CEE výhodou',
      'Výborný obchodní přehled a schopnost partnerství s businessem',
      'Zkušenosti s přeshraničními transakcemi a multijurisdikčními záležitostmi',
    ],
    featured: true,
  },
  {
    id: '2',
    slug: 'head-of-legal-cee-vienna',
    referenceCode: 'BS-2024-002',
    title: 'Head of Legal – CEE Region',
    titleCs: 'Head of Legal – Region CEE',
    location: 'Vienna',
    locationCs: 'Vídeň',
    type: 'inhouse',
    level: 'Executive',
    industry: 'Financial Services',
    industryCs: 'Finanční služby',
    shortDescription: 'Multinational financial services group seeking a senior legal leader to oversee operations across Central and Eastern Europe.',
    shortDescriptionCs: 'Nadnárodní skupina finančních služeb hledá seniorního právního lídra pro řízení operací ve střední a východní Evropě.',
    fullDescription: 'A leading multinational financial services group is seeking a Head of Legal for their CEE operations. Based in Vienna, this role offers the opportunity to lead a team of legal professionals and shape the legal strategy for a significant regional business.',
    fullDescriptionCs: 'Přední nadnárodní skupina finančních služeb hledá Head of Legal pro své CEE operace. Pozice sídlí ve Vídni a nabízí příležitost vést tým právních profesionálů a formovat právní strategii pro významný regionální byznys.',
    responsibilities: [
      'Lead the regional legal team across CEE markets',
      'Advise on regulatory compliance and banking law matters',
      'Support product development and new market entry initiatives',
      'Coordinate with group legal function on strategic matters',
      'Manage litigation and regulatory investigations',
    ],
    responsibilitiesCs: [
      'Vést regionální právní tým napříč trhy CEE',
      'Poradenství v oblasti regulatorní compliance a bankovního práva',
      'Podporovat vývoj produktů a iniciativy vstupu na nové trhy',
      'Koordinovat se skupinovou právní funkcí ve strategických záležitostech',
      'Řídit soudní spory a regulatorní vyšetřování',
    ],
    requirements: [
      '12+ years of legal experience in financial services',
      'Deep knowledge of CEE regulatory frameworks',
      'Experience leading cross-border legal teams',
      'Fluent English and German required',
      'Strong stakeholder management skills',
    ],
    requirementsCs: [
      '12+ let právní praxe ve finančních službách',
      'Hluboká znalost regulatorních rámců CEE',
      'Zkušenosti s vedením přeshraničních právních týmů',
      'Plynulá angličtina a němčina požadovány',
      'Silné dovednosti v řízení stakeholderů',
    ],
    featured: true,
  },
  {
    id: '3',
    slug: 'chief-legal-officer-dubai',
    referenceCode: 'BS-2024-003',
    title: 'Chief Legal Officer',
    titleCs: 'Chief Legal Officer',
    location: 'Dubai',
    locationCs: 'Dubaj',
    type: 'inhouse',
    level: 'C-Level',
    industry: 'Real Estate',
    industryCs: 'Nemovitosti',
    shortDescription: 'Major real estate development group in the UAE seeking a Chief Legal Officer to join their executive leadership.',
    shortDescriptionCs: 'Významná developerská skupina v SAE hledá Chief Legal Officer do svého exekutivního vedení.',
    fullDescription: 'One of the UAE\'s largest real estate development groups is seeking a Chief Legal Officer to join their executive team. This is a rare opportunity to shape the legal function of a market-leading organization with a diverse portfolio of landmark projects.',
    fullDescriptionCs: 'Jedna z největších developerských skupin v SAE hledá Chief Legal Officer do svého exekutivního týmu. Jedná se o vzácnou příležitost formovat právní funkci tržně vedoucí organizace s diverzifikovaným portfoliem významných projektů.',
    responsibilities: [
      'Serve as the principal legal advisor to the board and executive team',
      'Lead all corporate, commercial, and real estate legal matters',
      'Oversee regulatory compliance and government relations',
      'Manage significant litigation and dispute resolution',
      'Support major transactions and joint ventures',
    ],
    responsibilitiesCs: [
      'Působit jako hlavní právní poradce představenstva a exekutivního týmu',
      'Vést veškeré korporátní, obchodní a realitní právní záležitosti',
      'Dohlížet na regulatorní compliance a vztahy s vládou',
      'Řídit významné soudní spory a řešení sporů',
      'Podporovat velké transakce a joint ventures',
    ],
    requirements: [
      '18+ years of legal experience with significant real estate focus',
      'Experience at C-level or senior executive level',
      'Deep understanding of UAE legal and regulatory framework',
      'Track record in complex transactions and major projects',
      'Exceptional leadership and communication skills',
    ],
    requirementsCs: [
      '18+ let právní praxe s významným zaměřením na nemovitosti',
      'Zkušenosti na C-level nebo seniorní exekutivní úrovni',
      'Hluboká znalost právního a regulatorního rámce SAE',
      'Track record v komplexních transakcích a velkých projektech',
      'Výjimečné vedoucí a komunikační schopnosti',
    ],
    featured: true,
  },
  {
    id: '4',
    slug: 'partner-banking-finance-london',
    referenceCode: 'BS-2024-004',
    title: 'Partner – Banking & Finance',
    titleCs: 'Partner – Banking & Finance',
    location: 'London',
    locationCs: 'Londýn',
    type: 'lawfirm',
    level: 'Partner',
    industry: 'International Firm',
    industryCs: 'Mezinárodní kancelář',
    shortDescription: 'Top-tier international law firm seeking a banking & finance partner with strong portable practice.',
    shortDescriptionCs: 'Špičková mezinárodní advokátní kancelář hledá partnera pro banking & finance se silnou přenositelnou praxí.',
    fullDescription: 'A leading international law firm is seeking a partner to join their market-leading banking & finance practice in London. The firm offers an exceptional platform for partners with strong client relationships and the ambition to build their practice further.',
    fullDescriptionCs: 'Přední mezinárodní advokátní kancelář hledá partnera do své tržně vedoucí banking & finance praxe v Londýně. Kancelář nabízí výjimečnou platformu pro partnery se silnými klientskými vztahy a ambicí dále rozvíjet svou praxi.',
    responsibilities: [
      'Lead complex financing transactions for major clients',
      'Develop and grow client relationships',
      'Contribute to firm strategy and business development',
      'Mentor and develop junior team members',
      'Cross-sell firm services to existing and new clients',
    ],
    responsibilitiesCs: [
      'Vést komplexní financové transakce pro významné klienty',
      'Rozvíjet a pěstovat klientské vztahy',
      'Přispívat ke strategii kanceláře a rozvoji byznysu',
      'Mentorovat a rozvíjet juniorní členy týmu',
      'Cross-sellovat služby kanceláře stávajícím i novým klientům',
    ],
    requirements: [
      'Qualified in England & Wales with significant banking & finance experience',
      'Demonstrable portable practice and client following',
      'Strong reputation in the market',
      'Excellent business development track record',
      'Collaborative leadership style',
    ],
    requirementsCs: [
      'Kvalifikace v Anglii a Walesu s významnou banking & finance zkušeností',
      'Prokazatelná přenositelná praxe a klientská základna',
      'Silná reputace na trhu',
      'Výborný track record v business developmentu',
      'Spolupracující vedoucí styl',
    ],
    featured: false,
  },
  {
    id: '5',
    slug: 'deputy-general-counsel-prague',
    referenceCode: 'BS-2024-005',
    title: 'Deputy General Counsel',
    titleCs: 'Deputy General Counsel',
    location: 'Prague',
    locationCs: 'Praha',
    type: 'inhouse',
    level: 'Executive',
    industry: 'Manufacturing',
    industryCs: 'Výroba',
    shortDescription: 'Global manufacturing company seeking a Deputy General Counsel to support the GC and lead European legal operations.',
    shortDescriptionCs: 'Globální výrobní společnost hledá Deputy General Counsel na podporu GC a vedení evropských právních operací.',
    fullDescription: 'A global manufacturing company with significant European operations is seeking a Deputy General Counsel based in Prague. This role offers the opportunity to work closely with the General Counsel while leading the European legal team.',
    fullDescriptionCs: 'Globální výrobní společnost s významnými evropskými operacemi hledá Deputy General Counsel se sídlem v Praze. Tato role nabízí příležitost úzce spolupracovat s General Counsel a zároveň vést evropský právní tým.',
    responsibilities: [
      'Support the General Counsel on strategic matters',
      'Lead the European legal team on day-to-day matters',
      'Manage commercial contracts and negotiations',
      'Oversee employment law matters across Europe',
      'Coordinate with external counsel on complex matters',
    ],
    responsibilitiesCs: [
      'Podporovat General Counsel ve strategických záležitostech',
      'Vést evropský právní tým v každodenních záležitostech',
      'Řídit obchodní smlouvy a vyjednávání',
      'Dohlížet na pracovněprávní záležitosti v Evropě',
      'Koordinovat s externími advokáty v komplexních záležitostech',
    ],
    requirements: [
      '10+ years of legal experience, preferably in manufacturing or industrial sector',
      'Experience managing or leading legal teams',
      'Strong commercial contracts experience',
      'Fluent English; German or other European languages advantageous',
      'Pragmatic, business-oriented approach',
    ],
    requirementsCs: [
      '10+ let právní praxe, ideálně ve výrobním nebo průmyslovém sektoru',
      'Zkušenosti s řízením nebo vedením právních týmů',
      'Silné zkušenosti s obchodními smlouvami',
      'Plynulá angličtina; němčina nebo jiné evropské jazyky výhodou',
      'Pragmatický, byznysově orientovaný přístup',
    ],
    featured: false,
  },
  {
    id: '6',
    slug: 'regional-legal-director-emea-munich',
    referenceCode: 'BS-2024-006',
    title: 'Regional Legal Director – EMEA',
    titleCs: 'Regionální právní ředitel – EMEA',
    location: 'Munich',
    locationCs: 'Mnichov',
    type: 'inhouse',
    level: 'Executive',
    industry: 'Technology',
    industryCs: 'Technologie',
    shortDescription: 'US technology company expanding European presence seeks Regional Legal Director for EMEA operations.',
    shortDescriptionCs: 'Americká technologická společnost rozšiřující evropskou přítomnost hledá regionálního právního ředitele pro operace EMEA.',
    fullDescription: 'A major US technology company is significantly expanding its European presence and seeking a Regional Legal Director for EMEA. Based in Munich, this role will be instrumental in building the European legal function from the ground up.',
    fullDescriptionCs: 'Významná americká technologická společnost významně rozšiřuje svou evropskou přítomnost a hledá regionálního právního ředitele pro EMEA. Pozice sídlí v Mnichově a bude klíčová při budování evropské právní funkce od základů.',
    responsibilities: [
      'Build and lead the EMEA legal function',
      'Advise on product launches and market entry strategies',
      'Manage data privacy and regulatory compliance',
      'Support commercial partnerships and negotiations',
      'Coordinate with US headquarters on global matters',
    ],
    responsibilitiesCs: [
      'Budovat a vést právní funkci EMEA',
      'Poradenství při uvádění produktů a strategiích vstupu na trh',
      'Řídit ochranu osobních údajů a regulatorní compliance',
      'Podporovat obchodní partnerství a vyjednávání',
      'Koordinovat s americkým ústředím v globálních záležitostech',
    ],
    requirements: [
      '12+ years of legal experience, ideally in technology sector',
      'Experience building legal teams or functions',
      'Strong knowledge of EU data privacy and technology regulation',
      'Fluent English and German',
      'Entrepreneurial mindset and hands-on approach',
    ],
    requirementsCs: [
      '12+ let právní praxe, ideálně v technologickém sektoru',
      'Zkušenosti s budováním právních týmů nebo funkcí',
      'Silná znalost EU ochrany dat a technologické regulace',
      'Plynulá angličtina a němčina',
      'Podnikatelské myšlení a praktický přístup',
    ],
    featured: false,
  },
  {
    id: '7',
    slug: 'senior-legal-counsel-ma-warsaw',
    referenceCode: 'BS-2024-007',
    title: 'Senior Legal Counsel – M&A',
    titleCs: 'Senior Legal Counsel – M&A',
    location: 'Warsaw',
    locationCs: 'Varšava',
    type: 'inhouse',
    level: 'Senior',
    industry: 'Private Equity',
    industryCs: 'Private Equity',
    shortDescription: 'Leading private equity firm seeking a senior M&A legal counsel to support investment activity across CEE.',
    shortDescriptionCs: 'Přední private equity firma hledá seniorního M&A legal counsel na podporu investiční aktivity v CEE.',
    fullDescription: 'A leading private equity firm with significant assets under management is seeking a Senior Legal Counsel to join their Warsaw office. This role focuses on supporting the firm\'s investment activity across Central and Eastern Europe.',
    fullDescriptionCs: 'Přední private equity firma s významnými aktivy pod správou hledá Senior Legal Counsel do své varšavské kanceláře. Tato role se zaměřuje na podporu investiční aktivity firmy ve střední a východní Evropě.',
    responsibilities: [
      'Support M&A transactions from due diligence through closing',
      'Coordinate legal workstreams on portfolio company matters',
      'Manage external counsel on transactions',
      'Support fund formation and investor relations',
      'Advise on portfolio company governance',
    ],
    responsibilitiesCs: [
      'Podporovat M&A transakce od due diligence po closing',
      'Koordinovat právní workstreamy v záležitostech portfoliových společností',
      'Řídit externí advokáty na transakcích',
      'Podporovat zakládání fondů a vztahy s investory',
      'Poradenství v oblasti governance portfoliových společností',
    ],
    requirements: [
      '8+ years of M&A experience, either in private practice or in-house at a PE firm',
      'Strong transactional skills and commercial awareness',
      'Experience with CEE transactions',
      'Fluent English; Polish advantageous',
      'Ability to work in fast-paced, deal-driven environment',
    ],
    requirementsCs: [
      '8+ let M&A zkušeností, buď v advokacii nebo in-house v PE firmě',
      'Silné transakční dovednosti a obchodní povědomí',
      'Zkušenosti s transakcemi v CEE',
      'Plynulá angličtina; polština výhodou',
      'Schopnost pracovat v rychlém, transakčně řízeném prostředí',
    ],
    featured: false,
  },
  {
    id: '8',
    slug: 'partner-corporate-ma-budapest',
    referenceCode: 'BS-2024-008',
    title: 'Partner – Corporate/M&A',
    titleCs: 'Partner – Corporate/M&A',
    location: 'Budapest',
    locationCs: 'Budapešť',
    type: 'lawfirm',
    level: 'Partner',
    industry: 'Regional Firm',
    industryCs: 'Regionální kancelář',
    shortDescription: 'Leading regional law firm seeking a corporate/M&A partner to lead their Hungarian practice.',
    shortDescriptionCs: 'Přední regionální advokátní kancelář hledá corporate/M&A partnera k vedení maďarské praxe.',
    fullDescription: 'A highly regarded regional law firm with offices across CEE is seeking a corporate/M&A partner to lead their Hungarian practice. This is an excellent opportunity for an experienced practitioner looking to build their own team.',
    fullDescriptionCs: 'Vysoce uznávaná regionální advokátní kancelář s pobočkami v CEE hledá corporate/M&A partnera k vedení maďarské praxe. Jedná se o vynikající příležitost pro zkušeného praktika, který chce vybudovat svůj vlastní tým.',
    responsibilities: [
      'Lead the Hungarian corporate/M&A practice',
      'Advise on significant transactions in the market',
      'Develop client relationships in Hungary and the region',
      'Build and mentor the local team',
      'Contribute to firm management and strategy',
    ],
    responsibilitiesCs: [
      'Vést maďarskou corporate/M&A praxi',
      'Poradenství při významných transakcích na trhu',
      'Rozvíjet klientské vztahy v Maďarsku a regionu',
      'Budovat a mentorovat lokální tým',
      'Přispívat k řízení a strategii kanceláře',
    ],
    requirements: [
      'Qualified in Hungary with 12+ years of corporate/M&A experience',
      'Strong reputation in the Hungarian legal market',
      'Existing client relationships',
      'Fluent Hungarian and English',
      'Entrepreneurial drive and leadership qualities',
    ],
    requirementsCs: [
      'Kvalifikace v Maďarsku s 12+ lety corporate/M&A zkušeností',
      'Silná reputace na maďarském právním trhu',
      'Existující klientské vztahy',
      'Plynulá maďarština a angličtina',
      'Podnikatelský drive a vedoucí kvality',
    ],
    featured: false,
  },
]

export function getJobBySlug(slug: string): Job | undefined {
  return jobsData.find(job => job.slug === slug)
}

export function getAllJobs(): Job[] {
  return jobsData
}

export function getFeaturedJobs(): Job[] {
  return jobsData.filter(job => job.featured)
}
